<section class="main-cnt">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12">
			<h1>Random Questions & Answers</h1>

				<h2>How did you get started in Web Design/Development?</h2>
				<p>My background coming out of college was graphic design. I had just gotten hired at Boeing and was working in the desktop support group. My co-worker and friend Christian Booth knew I was into graphic design and suggested I try designing and building a website. Build a website?? I had no idea what he was talking about so he quickly opened Notepad and typed in "hello world" and then added in some simple HTML to change the font color. That was my "holy crap" moment and was hooked right then and there. I bought a HTML book and never looked back. It's a pretty generic story, but it's crazy how you stumble across things in life and some of those things become one of your life long passions. Even though I'm embarking on a new journey in my career away from coding full time, I'll always have one hand in it, just like I'm doing right now writing this content!</p>
			
				<h2>Advice for someone starting out in their career:</h2>

				<p>My advice is pretty simple; don’t lose focus on your happiness and always keep your eyes open to opportunities. You want your career to be a fun journey and not a 30 year grind. If you ever start dreading going to work, it probably means you need a change. I’ve worked with a lot of folks who were miserable and whose only focus was on the next paycheck and their retirement. It was interesting learning why they never ventured to another company or position and the common thing I heard was that’s the way they were taught. Their generation and the previous generations worked at one company and then you retired so this is how they grew up thinking. I was on the tail end of this generation and after the 5 year mark at my first company got sucked into this mentality thinking I was going to retire there. The term my co-workers used was “lifer”. It’s funny how 5 years becomes 10, then 15, but I get it. You’re making a great salary, benefits are off the charts (my grad school was paid in full), 401k matching is awesome, you get comfortable. On the flip side though, how happy are you? It’s when I started at my new company that I had time to dwell on the previous 15 years and realized I wasn’t completely happy the entire time, and like I mentioned before, got in the “comfort” zone. If I could do things differently I probably would’ve ventured out and experienced other opportunities and worked for fun companies like the one I’m at now. The message for folks just embarking on their careers is to make sure to take some time to evaluate how happy you are with your job and field you’re in. You can also take it one step further and make mental notes of the particular aspects of your current job you like and dislike. This will be beneficial in helping pave the way for your next career move.</p>

				<h2>Advice for someone starting out in Web Development</h2>
				<p>I know the learning approach has changed since I first started. There is a wide assortment of development bootcamps for rapid learning, however I'm still a believer in getting a good handle on the bare bones fundamentals and then building your skills from there. I see folks jumping straight into Javascript or PHP tutorials with no understanding of basic HTML or how to build a basic web page and then wonder why they are so overwhelmed and confused. Ok, you built this JS calculator, can you now implement it into a website? I usally get a blank stare. Haha. My recommendation is to learn basic HTML and CSS and build a bare bones website and then start manipulating the layout and aesthetics. Again, learn and get a good understanding of the foundation and fundamentals. Diving in head first to PHP or other languages will only cause you frustration and confusion. At least that was my experience early on. 

				<h2>What are your hobbies outside of work?</h2>

				<p>I’d say my number one hobby outside of work is training at the gym. It's an addiction and has been a part of my lifestyle for over 20 years so I’m not sure if that counts as a hobby or not, but I love it. When it comes down to it I'm a gym rat for life! I’ve been into athletics my entire life and pumping iron just stuck as soon as I lifted my first weight in high school. I follow the sport of bodybuilding year round and enjoy reading up on new training techniques and nutrition. I recently took up cycling so am on my bike the days I'm not in the gym. </p> 

				<p>Golf is another passion of mine I took up during college. Unfortunately where we live it’s something I don’t play year round however my yearly trip to Hawaii to visit my family allows me to get a few rounds in during the winter months. There is so much mental aspects of golf it can drive you crazy at times, but it’s a sport where you’re constantly thinking which is the fun part. As I’ve gotten older the game has become more fun as I’m not as competitive (less cussing, throwing clubs haha) and play for the fun of it. I get to drink a few beers, have some laughs  and catch up with my buddies.</p>

				<p>Food and craft beers are some other things I really enjoy. I’ve really only gotten into craft beers the past few years and have taken the time to really learn about the different varieties. We’re spoiled with good beer up here in the Northwest (Washington/Oregon) along with the food scene thriving every year. There’s nothing better than a cold IPA from a brewery right in your backyard! So what's my favorite brewery? Well, there are too many to name, but as of right now I'd have to say Breakside Brewery in Oregon hands down! Sorry Washington.</p>

				<h2>Advice for folks starting out on an exercise regiment:</h2>

				<p>First off I’m always excited to hear friends and family members, friends of friends or whomever who decide to take an active approach in bettering their health. As much as I enjoy eating good food and drinking delicious craft beers, I’m also a bonafide gym junkie and health and fitness advocate. There are hundreds of approaches I read about in various forums and magazines, however when someone asks me how to start on an exercise regiments, I tell them to keep it simple. It’s not rocket science when it comes to diet and exercise however you need a plan and you need to ‘ease’ into those changes. The one word I use a lot is ‘moderation’ because a lot of folks I talk to don’t have that word in their vocabulary or have no idea what that means. Cheat foods, etc. are ok, but you should sprinkle those things in "moderation". If you eat fast food 5 days a week, try cutting that down to 4 times, then 3 times, etc. The same goes for exercise (e.g. - gym, walk, bike), start off slow doing 30 mins a day a few days a week, then keep increasing it along with intensity. The mistake I see all the time is people doing just the opposite of this. My fitness and bodybuilding peeps know exactly what I’m talking about. It’s usually January (famous New Year's resolution, hehe), they go on a hardcore crash diet and work out balls to the wall 7 days a week right out of the gate. What happens? Well it’s called burnout. I’ll see these folks in the gym for a couple weeks, see all the posts on Facebook on how they’re “killing it” in the gym, ran 10 miles on the treadmill, down 5 pounds and then all a sudden disappear. I’ll run into them a while later only to hear how they were sore for 2 weeks, miserable and couldn’t stand the diet and gave up. It’s all because integrating healthy habits to your daily regiment is a lifestyle change that you need to ease into it with baby steps.  Choose forms of exercise that are fun and enjoyable for yourself. Slowly integrate more healthy foods into your diet while minimizing the bad stuff, while…still allowing for cheat meals or snacks. And lastly who ever said you have to join a gym to get excercise???? Find something fun you enjoy doing where you're actually "moving" and stick to those things or join Planet Fitness...I'm joking. Haha. Don't join Planet Fitness. </p>

			</div>
		</div>
	</div>
</section>