<section class="main-cnt">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12">
				<h1>About Marc Takeuchi</h1>
				<p>
				I was born in Hawaii (Honolulu) and did most of my growing up in Seattle. My entire family still reside over there and I will always call it my home away from home. The laid back "island style" runs through me and is what has kept me level headed and relaxed my whole life. The people and atmosphere there are definitely one of a kind in the world.<p> I received my <strong>Bachelor of Fine Arts (BFA) </strong>in<strong> Graphics/Media Design</strong> from <strong>Washington State University</strong> (GO COUGS!). I was the only one my particular year that applied for the BFA program with a graphic design emphasis and got accepted on my first try. Upon graduating I had the opportunity to do a 6-month internship on campus at the Information Technology graphics lab. My responsibilities included printing, graphic design, photography as well as digital enhancement.</p>

				<p>When I returned home to Seattle I hooked up with a temp agency while I was applying for graphic design jobs. After working a handful of office jobs I was offered a 10 day contract with Boeing as an office admin. To make a long story short that 10 day contract turned into 10 months and eventually my foot in the door as a full time employee.  What I learned during my contract period is how diverse the company was in regards to its operation and that there was a lot more than just building airplanes. This was the first major shift in my career focusing on business, Information Systems and Technology. It was also during this period where I was introduced to web design which would end up having a huge influence in my career. Having had little to no business experience from college I enrolled in the graduate program at City University and received my <strong>MBA </strong>in<strong> Information Systems</strong>. </p>

				<p>I currently work for <a href="http://www.seattlewebdesign.com" title="Seattle Web Design" target="_blank">efelle creative</a> a web design firm in downtown Seattle. The owner is a good childhood friend of mine and as they say, it was destined that we be on the same team at some point in our lives. That time is now! I recently moved positions from a Senior Front End Web Developer to a Online Marketing Consultant. I feel blessed to be part of such a great company and <a href="http://www.seattlewebdesign.com/staff" title="team efelle" target="_blank">team</a>. </p>
				    
				<p>Outside of work my hobbies include training at the gym and playing golf both of which I relate to my career and work ethic. Both require focus, dedication, patience and concentration. The best part is you're constantly challenging and pushing yourself. The most important thing is I'm having fun and able spend time and catch up with friends. I've learned to incorporate these criteria into my career path and so far have had a fun journey "on and off the course". My other hobbies include cooking, reading up on sports nutrition and training, watching movies, online shopping baby!, hanging out with friends, going to Hawaii to spend time with my family and sometimes...just being a home body and relaxing!</p>

				<p>Lastly I wanted to talk about a piece of advice I received while playing golf. A while back my friend and I got paired with an older woman from Australia who happened to be out of all things, a sports psychologist. As the round went on the conversation came up about how golf was such a mentally frustrating game. She told us that a lot of golfers have one critical flaw in common; we concentrate on the end result rather than the next shot. When you do this you quickly lose focus on the current task at hand. I thought about this for a minute and realized she was right! I've come to learn and use this same technique in my everyday life and career. Having patience and doing things one step at a time has been a big factor in my achievements. In regards to the round of golf that day, I ended up shooting a 77, one of the best rounds of my life!</p>
			</div>
		</div>
	</div>
</section>